"""Add description, created_at and file_video_path to video table

Revision ID: 033ae1571af5
Revises: 90b93e261e1a
Create Date: 2025-05-30 09:12:02.400438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033ae1571af5'
down_revision: Union[str, None] = '90b93e261e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('file_video_path', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'created_at')
    op.drop_column('videos', 'file_video_path')
    op.drop_column('videos', 'description')
    # ### end Alembic commands ###
