"""Add subs in user-data

Revision ID: 1586939d8715
Revises: f0906aa806de
Create Date: 2025-05-13 14:00:28.976464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1586939d8715'
down_revision: Union[str, None] = 'f0906aa806de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subs_association_table',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('sub_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users_data.id'], ),
    sa.ForeignKeyConstraint(['sub_id'], ['users_data.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'sub_id')
    )
    op.add_column('users_data', sa.Column('subscribers_count', sa.Integer(), nullable=False))
    op.add_column('users_data', sa.Column('subscribtions_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_data', 'subscribtions_count')
    op.drop_column('users_data', 'subscribers_count')
    op.drop_table('user_subs_association_table')
    # ### end Alembic commands ###
