"""Remove all previous versions.

Revision ID: 5c8f38d2a09b
Revises: 
Create Date: 2025-06-07 11:34:02.015789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8f38d2a09b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=False),
    sa.Column('subscribers_count', sa.Integer(), nullable=False),
    sa.Column('subscribtions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['users_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subs_association_table',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('sub_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['sub_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'sub_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credits_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credits_id'], ['users_credits.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['users_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('file_video_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['video_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_likes_association_table',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('users_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'users_id')
    )
    op.create_table('video_tags_association_table',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['video_tags.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_tags_association_table')
    op.drop_table('video_likes_association_table')
    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('user_subs_association_table')
    op.drop_table('users_profiles')
    op.drop_table('video_tags')
    op.drop_table('video_statuses')
    op.drop_table('users_statuses')
    op.drop_table('users_roles')
    op.drop_table('users_credits')
    # ### end Alembic commands ###
