"""Add new table: VideoStatus. Add relationship between video and video_status as many to one.

Revision ID: 7a902ce63f8a
Revises: 033ae1571af5
Create Date: 2025-05-30 09:49:00.099690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a902ce63f8a'
down_revision: Union[str, None] = '033ae1571af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('videos', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'videos', 'video_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'status_id')
    op.drop_table('video_statuses')
    # ### end Alembic commands ###
