"""rename vido.name -> video.title

Revision ID: 90b93e261e1a
Revises: 1586939d8715
Create Date: 2025-05-27 23:00:53.763835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b93e261e1a'
down_revision: Union[str, None] = '1586939d8715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('videos', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###
