"""Replace association table for subs with new table, that represents many to many, but with fields. Add SubLine and SubLevel tables.

Revision ID: b644d3faea8a
Revises: 5c8f38d2a09b
Create Date: 2025-06-07 12:34:52.302452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b644d3faea8a'
down_revision: Union[str, None] = '5c8f38d2a09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_subscriptions_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_subscriptions_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('sub_id', sa.UUID(), nullable=False),
    sa.Column('subscription_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['sub_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['subscription_level_id'], ['users_subscriptions_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_subs_association_table')
    op.add_column('users_profiles', sa.Column('subscriptions_count', sa.Integer(), nullable=False))
    op.drop_column('users_profiles', 'subscribtions_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('subscribtions_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users_profiles', 'subscriptions_count')
    op.create_table('user_subs_association_table',
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sub_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users_profiles.id'], name='user_subs_association_table_author_id_fkey'),
    sa.ForeignKeyConstraint(['sub_id'], ['users_profiles.id'], name='user_subs_association_table_sub_id_fkey'),
    sa.PrimaryKeyConstraint('author_id', 'sub_id', name='user_subs_association_table_pkey')
    )
    op.drop_table('users_subscriptions_lines')
    op.drop_table('users_subscriptions_levels')
    # ### end Alembic commands ###
